### PR TITLE
Porting to CoreCLR

### PR DESCRIPTION
**Pull request by DaveVdE**
Right off the bat, this is my ~~first~~ second PR of this magnitude like... ever. So I wanted to open a PR asap to get the discussion going.

### CODE REVIEW

**Comment by DaveVdE** [comment]
Wait, what are all of these commits?

**Comment by nblumhardt** [comment]
Hi @DaveVdE,

Not 100% certain, but develop was behind master so I've now updated it. At first sight I thought that should have been sufficient to resolve it, but you may need to pull upstream/develop into your repo and rebase/re-apply your changes to it.

Short on time this morning, but let me know if you don't find a quick fix and I can look into it later this week.

All the best,
Nick

**Comment by DaveVdE** [comment]
I'm currently on vacation, and connectivity leaves much to be desired. I'll
be able to spend some time this week, though.

**Comment by DaveVdE** [comment]
Okay, took a while to figure it out, but I've got the right set of changes now.

**Comment by DaveVdE** [comment]
Do we need to move projects into src/ and test/ subdirectories? I managed to create a Bash script but I'm going to need some help with the ps1.

In fact, all the projects build and test fine with `dotnet`, it's the building stuff that I don't understand.

**Comment by nblumhardt** [comment]
`src/` and `test/` is a convention most .NET Core projects are following. The build script at https://github.com/serilog/serilog might offer some insight into how the build might work.

**Comment by lvermeulen** [comment]
@DaveVdE @nblumhardt I can help out with this if you like. I used to be as confused as the next person, but I have 5 .netstandard conversions behind me now and I'm pretty sure I get it. It's also pretty easy to set up CI  with Appveyor.

**Comment by nblumhardt** [comment]
@lvermeulen thanks for the offer! @DaveVdE what are your thoughts?

**Comment by DaveVdE** [comment]
I'd be happy to hand this over. I'm a bit short on time right now, and powershell and appveyor really aren't my strong points.

**Comment by lvermeulen** [comment]
@nblumhardt @DaveVdE 
Cool, then I'm submitting a PR with the entire conversion. You can have a look at the results in Appveyor [here](https://ci.appveyor.com/project/lvermeulen/sprache). Should this PR go to master or develop?

@nblumhardt Before merging this you would need to open a free account with Appveyor and add a new project from your Sprache repo. Then in your account dropdown, you select Encrypt Data, enter your NuGet API key and put the result in appveyor.yml where it says:

`
api_key:
  secure: [your encrypted key goes here]
`

Just one question: is TinyTemplates a sample or a NuGet package that should be published? Right now it's configured as a NuGet package but it's easily changed.

Notes:
* AppVeyor will only build on a commit to master (can be changed in appveyor.yml)
* AppVeyor always builds your packages, but will only publish them when you commit a tag (can be changed in appveyor.yml)

**Comment by nblumhardt** [comment]
Thanks @lvermeulen that's looking great! I'm involved in a few projects that use AppVeyor, shouldn't be too tricky to set up.

I've just changed the default branch of this repo to `develop` (FYI @mikehadlow) so that PRs go there by default - that's the right branch to target.

TinyTemplates is a sample, it shouldn't be an artifact.

One thought - does the build script detect when it's on a non-master branch and append a tag to the version? In [Serilog](https://github.com/serilog/serilog), master branch builds are published with versions like 1.2.3 and dev branch builds go out as e.g. 1.2.3-dev-nnnnn, which is working nicely.

Cheers!

**Comment by lvermeulen** [comment]
@nblumhardt Okay I will move the TinyTemplates project into samples.

I see that Serilog does the version suffix in their build script, I'll take a look and see if I understand what's going on.

**Comment by nblumhardt** [comment]
Thanks again for moving this forward @DaveVdE. We should have a 'dev' package on NuGet soon, just ironing out a couple of publishing wrinkles.

**Pull request closed without merging**
