### PR TITLE
Improve Parse.Ref

### PR DESCRIPTION
**Pull request by marcin-golebiowski**
It looks like `Parse.Ref` is having some problems when used heavily together with `Or`.
Please take a look at my fix, a unit test. 

There is also workaround but I would prefer not to use it.
The workaround:
 * Change  `Parse.Ref(() => parser)` to `Parse.Ref(() => parser.Named("unique_name"))`

Best regards,
Marcin

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the PR, Marcin 👍 

Seems like a bug/design limitation of memos, though not having been in the codebase for a while, I can't immediately spot it... happy to push forward with the fix as-is, but if you (or anyone following along) can spot the underlying issue, it'd be great to be able to address it at a lower level 🤔

**Comment by marcin-golebiowski** [comment]
I will try to create additional unit tests later today to check if the fix doesn't break anything.

**Comment by marcin-golebiowski** [comment]
@nblumhardt Please find my latest changes. 

I think the latest commit contains proper solution to the problem.
I think it's better than my original one.
The initial and second solution solves #166 

Best regards,
Marcin

**Comment by nblumhardt** [comment]
Awesome! Thank you, Marcin 👍

**Pull request merged**
