### PR TITLE
Targeting .NET 8

### PR DESCRIPTION
**Pull request by brodny**

### CODE REVIEW

**Comment by fl3pp** [comment]
@brodny May I ask why you abandoned this PR? Is it because you didn't receive a response?

**Comment by johngit22** [comment]
I am not sure of what you are making reference to here ?

John Boyd 😊

**Comment by brodny** [comment]
@fl3pp No, not quite, I was doing it just for my own amusement ;) I created PR by accident before I had a chance to properly test it, and now I cannot dedicate the time it needs because of personal matters. I also had the ambition to enable nullable reference types for the project but same issues as above. Sorry about that but if you need .NET8 support, feel free to take this PR and move on, I won't mind ;)

**Comment by johngit22** [comment]
Thanks, 😊 that is fine 🙂 All is good 😊

**Comment by fl3pp** [comment]
Sorry for the confusion! I was reading about the issue #194 and wondered why this PR was closed. Seems like I inferred too much here.

Anyway, thanks to both of you for the quick replies

**Comment by johngit22** [comment]
No worries. 👍☺️☺️ please stay in touch 😊..

**Pull request closed without merging**
